version: '3'
services:
  redis:
    image: redis:7.0.5
    container_name: code-gen-redis
    ports:
      - "16379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=101807
    command: redis-server --appendonly yes
    restart: always

volumes:
  redis-data:
